// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlr8PAlF7Zb_wrdOJ6VCvLgqUNvSclKCI',
    appId: '1:559238252587:web:58755305723532ae3fc26e',
    messagingSenderId: '559238252587',
    projectId: 'push-notification-exampl-2a195',
    authDomain: 'push-notification-exampl-2a195.firebaseapp.com',
    storageBucket: 'push-notification-exampl-2a195.firebasestorage.app',
    measurementId: 'G-MPTVKG9DNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBmpb7WUg-uKFA5e9Esq0WpPiNGlkvL6M',
    appId: '1:559238252587:android:0d7689e87c6e58273fc26e',
    messagingSenderId: '559238252587',
    projectId: 'push-notification-exampl-2a195',
    storageBucket: 'push-notification-exampl-2a195.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Mo2Xp2lbNjem5fPbOa9-BnZvOZrAqIo',
    appId: '1:559238252587:ios:198ec75f7237b9163fc26e',
    messagingSenderId: '559238252587',
    projectId: 'push-notification-exampl-2a195',
    storageBucket: 'push-notification-exampl-2a195.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Mo2Xp2lbNjem5fPbOa9-BnZvOZrAqIo',
    appId: '1:559238252587:ios:198ec75f7237b9163fc26e',
    messagingSenderId: '559238252587',
    projectId: 'push-notification-exampl-2a195',
    storageBucket: 'push-notification-exampl-2a195.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlr8PAlF7Zb_wrdOJ6VCvLgqUNvSclKCI',
    appId: '1:559238252587:web:308ca0349d2cf5763fc26e',
    messagingSenderId: '559238252587',
    projectId: 'push-notification-exampl-2a195',
    authDomain: 'push-notification-exampl-2a195.firebaseapp.com',
    storageBucket: 'push-notification-exampl-2a195.firebasestorage.app',
    measurementId: 'G-K0PE00KFVJ',
  );
}
